### ISSUE TITLE
Upgrade tailwind to v1

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/contratospr-web#13]
https://tailwindcss.com/docs/upgrading-to-v1

**Comment by akoepcke** [comment]
@jpadilla Do you mind if I give it a try?

**Comment by jpadilla** [comment]
@akoepcke we would love some help with this, thanks!

We still need to improve documentation for this project, but you should be able to run this using the production API.

```
$ API_URL="https://api.contratospr.com/v1" npm run dev
```

**Comment by jpadilla** [comment]
Done in #139
