### ISSUE TITLE
Rediseñar pagina de Entidades

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/contratospr-web#22]
Pagina de entidades necesita un rediseño.
- La meta es poder mostrar todos los contratos y servicios de una manera usable.

**Comment by jpadilla** [comment]
Just added pagination to contracts. Will condense services/contractors into something like this:
<img width="978" alt="Screen Shot 2019-08-18 at 9 36 51 AM" src="https://user-images.githubusercontent.com/83319/63225286-1bfaf000-c19c-11e9-82c6-f4514cffc7dc.png">
