### ISSUE TITLE
Inspiration: USAspending.gov

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/contratospr-web#3]
Recently found about https://www.usaspending.gov which is definitely a project to look up to(it's also open source). contratospr.com aims to be pretty similar but obviously scoped to Puerto Rico.

Their [advanced search](https://www.usaspending.gov/#/search) is what our search should aim to be like. Great balance between filtering, searching, and visualization.

Other interesting things:

https://datalab.usaspending.gov
Spending Explorer: https://www.usaspending.gov/?#/explorer
Agency Profile: https://www.usaspending.gov/#/agency/1068

**Comment by Jpadilla1** [comment]
I can take the first stab at this UI if it's what we want to go forward with.

**Comment by jpadilla** [comment]
As discussed with @Jpadilla1, I'm currently taking a rough stab at this and should have something to share soon.

**Comment by jpadilla** [comment]
work in progress...

<img width="1321" alt="Screen Shot 2019-05-11 at 2 24 33 PM" src="https://user-images.githubusercontent.com/83319/57573669-2b2e0d00-73f9-11e9-9c53-7051767e7181.png">
